[package]
name = "communities"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "communities"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

communities_integrity = { workspace = true } 
